# Generated by Django 4.1.5 on 2023-01-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='confirmpassword',
        ),
    ]
