# Generated by Django 4.1.5 on 2023-01-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_usermodel_confirmpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='confirmpassword',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='fullname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=12),
        ),
    ]
