# Generated by Django 4.1.5 on 2023-01-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_usermodel_confirmpassword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='confirmpassword',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=12),
        ),
    ]
