# Generated by Django 4.1.5 on 2023-01-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_usermodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='date',
        ),
    ]
