# Generated by Django 4.1.5 on 2023-01-25 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_usermodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='date',
            field=models.DateTimeField(default=datetime.timezone),
        ),
    ]
