# Generated by Django 4.1.5 on 2023-01-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_usermodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='date',
            field=models.DateField(verbose_name='2022-01-01T12:00:00'),
        ),
    ]
